USE [master]
GO

/****** Object:  Database [ContactInformation]    Script Date: 5/2/2018 9:07:56 AM ******/
DROP DATABASE [ContactInformation]
GO

/****** Object:  Database [ContactInformation]    Script Date: 5/2/2018 9:07:56 AM ******/
CREATE DATABASE [ContactInformation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactInformation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ContactInformation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContactInformation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ContactInformation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ContactInformation] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactInformation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactInformation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactInformation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactInformation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactInformation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactInformation] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactInformation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContactInformation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactInformation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactInformation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactInformation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactInformation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactInformation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactInformation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactInformation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactInformation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContactInformation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactInformation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactInformation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactInformation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ContactInformation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactInformation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ContactInformation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactInformation] SET RECOVERY FULL 
GO

ALTER DATABASE [ContactInformation] SET  MULTI_USER 
GO

ALTER DATABASE [ContactInformation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactInformation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactInformation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactInformation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContactInformation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactInformation] SET QUERY_STORE = OFF
GO

USE [ContactInformation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ContactInformation] SET  READ_WRITE 
GO


